#include <algorithm>
#include <cstdlib>
#include <iostream>
#include <unordered_map>

#include "getinput.hpp"

int solutionToPuzzleOne(const data &convertedData);
int solutionToPuzzleTwo(const data &convertedData);

/**
 * @brief Function used for testing purposes
 */
int main() {
  data convertedData = parseData("data/data.txt");

  int totalDifference = solutionToPuzzleOne(convertedData);
  std::cout << "Solution to puzzle 1: " << totalDifference << std::endl;

  int totalSimilarityScores = solutionToPuzzleTwo(convertedData);
  std::cout << "Solution to puzzle 2: " << totalSimilarityScores << std::endl;

  return 0;
}

std::vector<std::vector<std::pair<int, int>>> getAntennaPositions(const data &map, int height, int width);

/**
 * @brief returns the solution to the problem stated by AOC2024::day08::1 with
 * the given input data
 *
 * The first problem of the third day of AOC2024 consisted of finding the amount
 * of antinodes generated by the antennas on the map.
 *
 * @param[in] convertedData The formated input data necessary for the problem
 * @returns The difference between the two lists given as input data
 */
int solutionToPuzzleOne(const data &convertedData) {
  int height = convertedData.size();
  if (height == 0) return 0;
  int width = convertedData[0].size();
  if (width == 0) return 0;

  bool antinodespots[height][width];
  for (int h{0}; h < height; h++) {
    for (int w{0}; w < width; w++)
      antinodespots[h][w] = false;
  }
  
  std::vector<std::vector<std::pair<int, int>>> antennaPositions = getAntennaPositions(convertedData, height, width);
  for (auto &antennaSet : antennaPositions) {
    int numAntennas = antennaSet.size();
    for (int a1idx{0}; a1idx < numAntennas-1; a1idx++) {
      std::pair<int, int> &ant1 = antennaSet[a1idx];
      for (int a2idx{a1idx+1}; a2idx < numAntennas; a2idx++) {
        std::pair<int, int> &ant2 = antennaSet[a2idx];
        int dH = ant2.first - ant1.first, dW = ant2.second - ant1.second;
        int cH = ant1.first - dH, cW = ant1.second - dW;
        if (cH >= 0 && cH < height && cW >= 0 && cW < width)
          antinodespots[cH][cW] = true;
        cH = ant2.first + dH, cW = ant2.second + dW;
        if (cH >= 0 && cH < height && cW >= 0 && cW < width)
          antinodespots[cH][cW] = true;
      }
    }
  }

  int result{0};
  for (int h{0}; h < height; h++) {
    for (int w{0}; w < width; w++)
      if (antinodespots[h][w]) result++;
  }
  return result;
}

/**
 * @brief returns the solution to the problem stated by AOC2024::day08::2 with
 * the given input data
 *
 * The second problem of the third day of AOC2024 consisted of finding the amount
 * of antinodes generated by the antennas on the map.
 *
 * @param[in] convertedData The formated input data necessary for the problem
 * @returns The similarity between the two lists given as input data
 */
int solutionToPuzzleTwo(const data &convertedData) {
  int height = convertedData.size();
  if (height == 0) return 0;
  int width = convertedData[0].size();
  if (width == 0) return 0;

  bool antinodespots[height][width];
  for (int h{0}; h < height; h++) {
    for (int w{0}; w < width; w++)
      antinodespots[h][w] = false;
  }
  
  std::vector<std::vector<std::pair<int, int>>> antennaPositions = getAntennaPositions(convertedData, height, width);
  for (auto &antennaSet : antennaPositions) {
    int numAntennas = antennaSet.size();
    for (int a1idx{0}; a1idx < numAntennas-1; a1idx++) {
      std::pair<int, int> &ant1 = antennaSet[a1idx];
      for (int a2idx{a1idx+1}; a2idx < numAntennas; a2idx++) {
        std::pair<int, int> &ant2 = antennaSet[a2idx];
        int dH = ant2.first - ant1.first, dW = ant2.second - ant1.second;
        int cH = ant1.first, cW = ant1.second;
        while (cH >= 0 && cH < height && cW >= 0 && cW < width) {
          antinodespots[cH][cW] = true;
          cH -= dH; cW -= dW;
        }
        cH = ant2.first, cW = ant2.second;
        while (cH >= 0 && cH < height && cW >= 0 && cW < width) {
          antinodespots[cH][cW] = true;
          cH += dH; cW += dW;
        }
      }
    }
  }

  int result{0};
  for (int h{0}; h < height; h++) {
    for (int w{0}; w < width; w++)
      if (antinodespots[h][w]) result++;
  }
  return result;
}




std::vector<std::vector<std::pair<int, int>>> getAntennaPositions(const data &map, int height, int width) {
  int antennatypes{0};
  std::vector<std::vector<std::pair<int ,int>>> result;
  std::unordered_map<int, int> antennaidxmap;
  for (int h{0}; h < height; h++) {
    const std::vector<int> &row = map[h];
    for (int w{0}; w < width; w++) {
      int c = row[w];
      if (c != 46) { // 46 = '.' (ASCII)
        if (antennaidxmap.count(c) != 0)
          result[antennaidxmap[c]].push_back({h, w});
        else {
          antennaidxmap[c] = antennatypes++;
          result.push_back({{h, w}});
        }
      }
    }
  }
  return result;
}
